#!/usr/bin/bash
Tmp=/tmp/$$
Tmp1=/tmp/$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp1"' EXIT
rm -f "$Tmp"  >/dev/null 2>&1
rm -f "$Tmp1"  >/dev/null 2>&1
#================================================================
# HEADER
#================================================================
#% SYNOPSIS
#+    ${SCRIPT_NAME} [-hv] [-o[file]] args ...
#%
#% DESCRIPTION
#%    This is a script template
#%    to start any good shell script.
#%
#% OPTIONS
#%    -o [file], --output=[file]    Set log file (default=/dev/null)
#%                                  use DEFAULT keyword to autoname file
#%                                  The default value is /dev/null.
#%    -t, --timelog                 Add timestamp to log ("+%y/%m/%d@%H:%M:%S")
#%    -x, --ignorelock              Ignore if lock file exists
#%    -h, --help                    Print this help
#%    -v, --version                 Print script information
#%
#% EXAMPLES
#%    ${SCRIPT_NAME} -o DEFAULT arg1 arg2
#%
#================================================================
#- IMPLEMENTATION
#-    version         ${SCRIPT_NAME} 0.0.1
#-    author          MJE
#-    copyright       Copyright (c) All Rights Reserved
#-    license         All Rights Reserved
#-    script_id       0.0.1
#-
#================================================================
#  HISTORY
#     2024/11/15 : MJE : Script creation
# 
#================================================================
#  DEBUG OPTION
#    set -n  # Uncomment to check your syntax, without execution.
#    set -x  # Uncomment to debug this shell script
#
#================================================================
# END_OF_HEADER
#================================================================

#== needed variables ==#
SCRIPT_HEADSIZE=$(head -200 ${0} |grep -n "^# END_OF_HEADER" | cut -f1 -d:)
SCRIPT_NAME="$(basename ${0})"

#== usage functions ==#
usage() { printf "Usage: "; head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#+" | sed -e "s/^#+[ ]*//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" ; }
usagefull() { head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#[%+-]" | sed -e "s/^#[%+-]//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" ; }
scriptinfo() { head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#-" | sed -e "s/^#-//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g"; }


isnfs () {                                                                                                                       
    LOCAL=`stat -f -c %T "$1"`                                                                                                   
    if [ "$LOCAL" == "nfs" ]; then                                                                                               
         RETVAL="YES"                                                                                                             
    else                                                                                                                         
         RETVAL="NO"                                                                                                              
    fi                                                                                                                           
}

consolebar () {
    echo "********************************************************************************************"
}
consolemsg () {
#   consolebar
    echo "** $1"
#   consolebar
    A=$A
}
optconsolemsg () {
#    echo "** $1"
    A=$A
}

MESSAGE="Updated via snip script"
VIEWONLY=0
FN=""
ONELINER=""

while getopts "hm:vf:o:" arg
do
    case $arg in
        h) usagefull;
           exit 0;
           ;;
        m) MESSAGE="$OPTARG"
           ;;
        v) VIEWONLY=1
           ;;
        f) echo "$OPTARG" 
           FN=`echo "$OPTARG" | gawk '{split(tolower($0),A," ");sz="";for (v in A) {sz=sz toupper(substr( A[v],1,1)) substr(A[v],2);} print sz}'`
           ;;
        o) ONELINER="$OPTARG"
           ;;
    esac
done
shift $(($OPTIND - 1))

if [ $VIEWONLY -eq 1 ]; then
    cat "$1"
    exit
fi

#if [ $# -eq 1 ]; then
if [ 1 -eq 1 ]; then
    # File to write to
    if [ "$FN" == "" ]; then                                                                                               
        filename="$1"
    else
        if [ ! -f "./$FN" ]; then
            echo "$ONELINER" > "$FN"
            cat "$FN"
            filename="$FN"
            echo "$filename"
        else
            echo "$FN exists. Exiting..."
            exit
        fi
    fi
    file="/etc/scm/header/$filename"
    if [ "$filename" == "snip" ]; then
        echo "Cannot update the file [snip] this way"
        exit
    fi
    if [ -f "./$filename" ]; then
        # Check if the file exists
        if [ -f "/etc/scm/header/$filename" ]; then
          read -p "File '$file' already exists. Overwrite? (y/n): " answer
          case "$answer" in
            [Yy]* ) echo "Overwriting...";;
            [Nn]* ) echo "Exiting..."; exit;;
            * ) echo "Invalid input. Exiting..."; exit;;
          esac
        fi
        # Write to file
        cat "$filename" > "$file"
        ls -l "$file"
        D=`pwd`
        cd /etc/scm/header
        git add "$filename"
        git commit -m "$MESSAGE"
        cd "$D"
        ls -l /etc/scm/header
    else
        echo "File [$1] does not exist"
        exit
    fi
else
    echo "Incorrect number of arguments. Expected 1, got $#."
fi
