#!/usr/bin/bash
Tmp=/tmp/$$
Tmp1=/tmp/$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp1"' EXIT
rm -f "$Tmp"  >/dev/null 2>&1
rm -f "$Tmp1"  >/dev/null 2>&1

# Check if input file is provided
# if [ -z "$1" ]; then
#   echo "Usage: `basename "$0"` <input_file>"
#   exit 1
# fi

input_file="$1"
input_file="/dev/stdin"
output_file="${input_file%.*}.html"
extra="<!-- Google -->-"

# Count the number of lines in the input file
cat "$input_file"  | sed '/^$/d' | sort | uniq > $Tmp;
line_count=$(wc -l < "$Tmp");
num=$((line_count % 3))
if [ "$num" -eq 2 ]; then
    echo $extra >> $Tmp;
fi
if [ "$num" -eq 1 ]; then
    echo $extra >> $Tmp;
    echo $extra >> $Tmp;
fi

line_count=$(wc -l < "$Tmp");
num=$((line_count / 3))

# Split the input file into two temporary files
rm -f col_aa col_ab col_ac
split -l "$num" "$Tmp" "col_"
sed -i 's/^/<td>/'       col_aa
sed -i 's/$/<\/td>/'     col_aa
sed -i 's/^/<tr>/'       col_aa

sed -i 's/^/<td>/'       col_ab
sed -i 's/$/<\/td>/'     col_ab

sed -i 's/^/<td>/'       col_ac
sed -i 's/$/<\/td>/'     col_ac
sed -i 's/$/<\/tr>/'     col_ac

echo "<table border=0 cellpadding=1 cellspacing=1>"
paste -d "\n" col_aa col_ab col_ac
echo "</table>"


exit 0
